<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="InTheHand.Net.Bluetooth" Version="4.2.4" />
      <PackageReference Include="Tmds.DBus" Version="0.95.0" />
    </ItemGroup>

</Project>
